# Generated by Django 3.1.5 on 2021-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.TextField(default='test value'),
            preserve_default=False,
        ),
    ]
